### ISSUE TITLE
css() mutates object

### ISSUE THREAD

**Issue by benton-droplab** [css-hooks/css-hooks#167]
If you pass a css object as a prop, the object is mutated and in strict mode, this causes issues.

``` ts
import { css } from "./shared/css";
function Box(props) {
  return (
    <div
      style={css(props.css)}
    >
      {props.children}
    </div>
  );
}

function App() {
  return (
    <main>
      <Box
         flex={"row"}
         justify={"center"}
         css={{
	   background: "red",
	   hover: {
	      background: "blue"
	   }
	}}
      >
	Box
     </Box>
   </main>
  )
}

```

This won't work with strict mode, as the hover styles are lost.

**Comment by nsaunders** [comment]
Hi Benton, thanks for the report!

The `css` function does indeed mutate the object that is passed in, for performance reasons. But I'm happy to review this and see if it needs to change.

A couple of things...

1. Can you confirm please whether this is the type of error you're encountering?

![image](https://github.com/css-hooks/css-hooks/assets/2517229/98281eea-c070-4d73-baa6-eab3161c27a5)

If so, no need for a repro. Otherwise, if you could share a few more details about the error you're encountering, that would be fantastic.

2. Would you mind sharing your `./shared/css` module?

Thanks in advance for the info.

**Comment by b3nten** [comment]
No error, the style just looses it's selectors and only the base styles are present on the tag.

https://github.com/b3nten/ui/blob/main/output/react/components/Box.jsx

If you replace cssobj() with the raw props.css object it will not work. If you turn off strict mode, it will work again.

Here is the css module:
https://github.com/b3nten/ui/blob/main/output/react/components/shared/css.js

**Comment by b3nten** [comment]
Here I built a simple repro
https://github.com/b3nten/css-hooks-repro

**Comment by nsaunders** [comment]
I was able to reproduce the issue from a slightly different angle by making the following change to the React demo:

```diff
--- a/examples/react/src/App.tsx
+++ b/examples/react/src/App.tsx
@@ -2,6 +2,36 @@ import * as V from "varsace";
 import Logo from "./Logo";
 import { css } from "./css";
 
+const style = {
+  fontFamily: "Inter, sans-serif",
+  fontSize: "1.333rem",
+  fontWeight: 700,
+  letterSpacing: "-0.03em",
+  border: 0,
+  textDecoration: "none",
+  background: V.gray50,
+  color: V.white,
+  padding: "0.5em 0.75em",
+  display: "inline-block",
+  on: ($, { and }) => [
+    $("&:hover", {
+      background: V.blue40,
+    }),
+    $("&:active", {
+      background: V.red40,
+    }),
+    $("@media (prefers-color-scheme: dark)", {
+      background: V.gray70,
+    }),
+    $(and("@media (prefers-color-scheme: dark)", "&:hover"), {
+      background: V.blue50,
+    }),
+    $(and("@media (prefers-color-scheme: dark)", "&:active"), {
+      background: V.red50,
+    }),
+  ],
+};
+
 function App() {
   return (
     <div
@@ -28,38 +58,7 @@ function App() {
       <div style={{ fontSize: 192 }}>
         <Logo />
       </div>
-      <a
-        href="https://css-hooks.com/docs"
-        style={css({
-          fontFamily: "Inter, sans-serif",
-          fontSize: "1.333rem",
-          fontWeight: 700,
-          letterSpacing: "-0.03em",
-          border: 0,
-          textDecoration: "none",
-          background: V.gray50,
-          color: V.white,
-          padding: "0.5em 0.75em",
-          display: "inline-block",
-          on: ($, { and }) => [
-            $("&:hover", {
-              background: V.blue40,
-            }),
-            $("&:active", {
-              background: V.red40,
-            }),
-            $("@media (prefers-color-scheme: dark)", {
-              background: V.gray70,
-            }),
-            $(and("@media (prefers-color-scheme: dark)", "&:hover"), {
-              background: V.blue50,
-            }),
-            $(and("@media (prefers-color-scheme: dark)", "&:active"), {
-              background: V.red50,
-            }),
-          ],
-        })}
-      >
+      <a href="https://css-hooks.com/docs" style={css(style)}>
         Get started
       </a>
     </div>
```

Since I was able to reproduce the issue without involving [css-hooks-basic](https://github.com/nsaunders/css-hooks-basic), I'll address it here first, and I'll open a corresponding issue to review css-hooks-basic separately.

**Comment by b3nten** [comment]
awesome, thanks!
