### ISSUE TITLE
Naming convention for "recommended" hooks

### ISSUE THREAD

**Issue by nsaunders** [css-hooks/css-hooks#25]
As noted [here](https://x.com/agilecoder/status/1730237848127754243?s=20), I love @markdalgleish's naming convention for hooks. It seems so obvious to me now that the hook name should tell you exactly what it does, rather than just hinting at that with an alias.

Unfortunately, changing the names now in the bundled `recommended` object would represent a breaking change.

It's worth noting, however, that the reason the `recommended` object is bundled and re-exported from each framework-specific package, is to account for differences in naming conventions in each framework. For example, Solid users would expect kebab-cased hook names (`focus-within`), where React users are accustomed to camel-case (`focusWithin`). Mark's naming convention renders this a non-issue.

So here's what I propose:
1. Let's flag the existing `recommended` exports as `@deprecated`. (I don't think anyone's deeply invested yet, but I'd like to accumulate more issues before jumping to v2.)
2. A new package called `@css-hooks/recommended` which would export all of the recommended hooks with the new (framework-agnostic) naming convention.

If anyone has thoughts on this or might be interested in helping out, please let me know!

**Comment by markdalgleish** [comment]
This sounds good to me.

I think `recommended` should be a function, that way you can easily add new features without it being a breaking change, e.g.

```ts
createHooks(recommended({
  breakpoints: ['768px', '1024px'],
});
```

Which means this idea could be taken a lot further too:

```ts
createHooks(recommended({
  colorModes: true,
  breakpoints: ['768px', '1024px'],
  containers: {
    name: 'container',
    breakpoints: ['320px', '640px']
  },
  groups: true, // Based on this? https://tailwindcss.com/docs/hover-focus-and-other-states#styling-based-on-parent-state
});
```

Also, it might be a good idea to make everything in `recommended` opt-in so that it doesn't get confusing in the future trying to remember which things need to be enabled and which don't. For example, the current defaults would look like this:

```ts
createHooks(recommended({
  psuedoClasses: [
    ':hover',
    ':active',
    ':focus', // etc.
  ],
});
```

What I like about this is that it's a good balance of convenience and transparency. I feel like I have full control over the size of the CSS in the head, but I don't need to write low-level config.

**Comment by nsaunders** [comment]
Thanks Mark, so glad you were able to review the issue. The `recommended` function is a great idea. It hadn't occurred to me how to solve the problem of custom breakpoints etc. without resorting to fully custom hooks. I hope I'm not bothering you too much, but, if you manage to find the time to take this further, that would be amazing. If not, no worries at all!
