### ISSUE TITLE
how to use it in a component library?

### ISSUE THREAD

**Issue by lili21** [css-hooks/css-hooks#48]
is it suitable for a component library?

**Comment by nsaunders** [comment]
Hi @lili21, thanks for your interest. CSS Hooks works great for component libraries! In fact, the only setup required for someone using your component library is to add your hooks style sheet somewhere in their app as described in Step 3 of the [Getting started](https://css-hooks.com/docs/react/getting-started) guide. It's up to you how you'd like to document this for your users; or, if you wanted to hide CSS Hooks completely as a "private implementation detail", you could even create a simplified component wrapper around the `<style>` element, along the lines of [this example](https://github.com/markdalgleish/css-hooks-playground/blob/188a6deb9972b73e6f71d6a224c8e150b95b28ba/app/css-hooks.tsx#L24-L30) (although you might want to consider a more generic name in this case, e.g. `ComponentLibraryStyleSheet`).

Please let me know if you have any specific questions/concerns, and I'd be happy to discuss! Otherwise, I'll leave the issue open for a few days in case anyone else wants to chime in.
