### ISSUE TITLE
question regarding new merge functionality

### ISSUE THREAD

**Issue by cloudkite** [css-hooks/css-hooks#58]
First of all thanks for the library am enjoying it alot!

The new merge functionality is great and can see it being useful for builting abstractions on top of css-hooks.

However I did run into behaviour that was a bit unexpected and was unsure if it was intentional or not?

When I run :

```
css(
  {
      background: "blue",
      ":hover": { background: "pink" }
  },
  {
      background: "black",
  }
)
```

I was expecting 

```
{ background: "var(--somehash, pink) var(--somehash, black)" }
```

However the actual result is:

```
{ background: "black" }
```

Which means I lose the hover.

I think a good analogue is apply multiple css classes to an element.

```
 .style1 {
      background: blue;
      :hover: { background: pink; }
  }

  .style2 {
      background: black,
  }

<div class="style1 style2"/>
```

In this case its acts like deep merge and I think it would be more intuitive if passing multiple objects to css() behaved in the same way

**Comment by cloudkite** [comment]
Hi @nsaunders

I think its confusing due to the precedent set by html for example:

```
<style>
   button {
      color: blue;
      :hover {
         color: white;
      }
   }
</style>

<button style="color: black" />
```

Therefore it feels unexpected that the equivalent/similar code in react

```
function Button({ style }) {
    return <button style={css({ color: "blue", ":hover": { color: "white" } }, style)}/>
}

<Button style={{ color: "black" }} />
```

removes the hover

**Comment by cloudkite** [comment]
Another usecase would be for vanilla-extract recipe / stitches type abstractions on top of css-hooks:

```jsx

let Button = styled.button({
   base: {
     color: "grey",
     ":hover": {
         color: "white",
     },
   },
   variants: {
      kind: {
        primary: {
             color: "purple",
        },
        secondary: {
             color: "orange"
        },
      }
   },
});

<Button kind="primary" />
```

Would be nice to use the css function to merge the base and selected variants. However it feels unexpected that I lose the hover

**Comment by nsaunders** [comment]
Thanks for sharing some additional thoughts @cloudkite. I think I do understand the potential confusion around this issue. A small modification to one of your earlier examples paints a clear picture of why one might expect the behavior you described:

```html
<style>
  button {
    color: blue;
  }
  
  button:hover {
    color: red;
  }
  
  button {
    color: green;
  }
</style>
<button>test</button>
```

Indeed, the `color: green` declaration overrides the `color: blue` declaration (due to appearing later) but is overridden by `color: red` on hover. As you know, the `color: red` declaration wins in this case due to the higher specificity of the `button:hover` selector.

But imagine if specificity didn't exist. How would you selectively override the default color without overriding the hover color?

This is how I would do it:

```html
<style>
  button {
    color: blue;
  }
  
  button:hover {
    color: red;
  }
  
  button:not(:hover) {
    color: green;
  }
</style>
<button>test</button>
```

I'm not trying to present an abstract/theoretical argument here: Specificity just isn't a tool that's available in inline styles, unfortunately.

I'm also not sure there's a sorting/merging algorithm that can consistently make up the difference and meet every expectation. That's why I think the best we might be able to do is to use a simple heuristic to give people (who are aware of it) a predictable, even if non-ideal, result. Currently, with `sort` enabled, that heuristic is simply, "the last declaration wins". It's mentioned on the [API](https://css-hooks.com/docs/react/api) page, but I admit that it could be better-documented.

Hopefully there is a better solution out there that I just haven't discovered and/or fully understood yet, so let's keep the discussion open and please continue sharing your ideas!

**Comment by cloudkite** [comment]
Hi @nsaunders, thanks for taking the time to explain your thoughts around this 👍

I totally understand if deep merging is out of scope for this library, probably a good call as it likely would increase complexity.

I'm thinking of going down the road of maintaining an internal fork. In the current project I'm working on we want to migrate away from stitches and with a few changes I think we can use this as an underlying engine for that. Thanks for open sourcing this project, it has opened our eyes to a fresh and lightweight way of doing CSS-in-JS!

**Comment by nsaunders** [comment]
@cloudkite you're welcome to fork, of course; but, if this is something you'd prefer to avoid, you may be in luck with v2. I'm still experimenting, but I think I could provide an option to prioritize overrides with fairly minimal overhead. Whether to enable this option (or maybe it would even be the default), would probably depend on whether you prefer to keep CSS Hooks as a private implementation detail (i.e. type the `style` prop as `CSSProperties` - traditional inline style approach - probably better for a design system), or to expose the type enhanced with hooks (i.e. `CSSProperties & { overrides?: ... }`).

**Comment by cloudkite** [comment]
Closing in favor of https://github.com/css-hooks/css-hooks/discussions/61
